### ISSUE TITLE
[8] framechange is not deterministic

### ISSUE THREAD

**Issue by eek** [findie/FFmpeg#14]
I get weird different results from run to run:

Run 1:
![image](https://user-images.githubusercontent.com/2953026/45419735-cdda9400-b690-11e8-8143-8052b98172f0.png)

Run 2:
![image](https://user-images.githubusercontent.com/2953026/45419777-e185fa80-b690-11e8-9444-763e9ee193dd.png)

**Comment by legraphista** [comment]
Fixed in https://github.com/findie/FFmpeg/commit/c490a6de7168351f87c7cf6957acb6e8e724f188
